USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT
  D.YEAR_MONTH,
  C.CUSTOMER_REGION AS REGION,
  SUM(F.NET_SALES)  AS NET_REVENUE
FROM DM_PROJECT.GOLD.FACT_SALES F
JOIN DM_PROJECT.GOLD.DIM_CUSTOMER C
  ON F.C_CUSTKEY = C.C_CUSTKEY
JOIN DM_PROJECT.GOLD.DIM_DATE D
  ON F.ORDER_DATE = D.DATE
GROUP BY 1,2
ORDER BY 1,2;
