USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT
  D.YEAR,
  C.C_CUSTKEY,
  C.C_NAME          AS CUSTOMER_NAME,
  C.CUSTOMER_REGION AS REGION,
  SUM(F.NET_SALES)  AS NET_REVENUE
FROM DM_PROJECT.GOLD.FACT_SALES F
JOIN DM_PROJECT.GOLD.DIM_CUSTOMER C
  ON F.C_CUSTKEY = C.C_CUSTKEY
JOIN DM_PROJECT.GOLD.DIM_DATE D
  ON F.ORDER_DATE = D.DATE
WHERE D.YEAR = 1996
GROUP BY 1,2,3,4
ORDER BY NET_REVENUE DESC
LIMIT 10;
