USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT
  C.CUSTOMER_REGION AS REGION,
  AVG(F.L_DISCOUNT) AS AVG_DISCOUNT,
  SUM(F.NET_SALES)  AS TOTAL_NET_REVENUE
FROM DM_PROJECT.GOLD.FACT_SALES F
JOIN DM_PROJECT.GOLD.DIM_CUSTOMER C
  ON F.C_CUSTKEY = C.C_CUSTKEY
GROUP BY 1
ORDER BY AVG_DISCOUNT DESC;
