USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT
  P.P_BRAND         AS BRAND,
  P.P_MFGR          AS MANUFACTURER,
  SUM(F.NET_SALES)  AS NET_REVENUE,
  SUM(F.L_QUANTITY) AS UNITS_SOLD
FROM DM_PROJECT.GOLD.FACT_SALES F
JOIN DM_PROJECT.GOLD.DIM_PART P
  ON F.P_PARTKEY = P.P_PARTKEY
GROUP BY 1,2
ORDER BY NET_REVENUE DESC;
