USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT
  F.SHIP_MODE,
  AVG(F.DISPATCH_DAYS) AS AVG_DISPATCH_DAYS,
  SUM(F.L_QUANTITY)    AS VOLUME_UNITS,
  SUM(F.NET_SALES)     AS VOLUME_NET_REVENUE
FROM DM_PROJECT.GOLD.FACT_SALES F
GROUP BY 1
ORDER BY VOLUME_UNITS DESC;
