USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS DM_PROJECT;
USE DATABASE DM_PROJECT;

CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;


CREATE OR REPLACE TABLE DIM_DATE AS
WITH all_dates AS (
    SELECT O_ORDERDATE AS D FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
    UNION ALL
    SELECT L_SHIPDATE  AS D FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
)
SELECT DISTINCT
    D                                     AS DATE,
    YEAR(D)                               AS YEAR,
    MONTH(D)                              AS MONTH,
    DAY(D)                                AS DAY,
    TO_CHAR(D,'YYYY-MM')                  AS YEAR_MONTH,
    DAYOFWEEKISO(D)                       AS DOW_ISO,
    WEEKOFYEAR(D)                         AS WEEK_OF_YEAR
FROM all_dates
WHERE D IS NOT NULL;


CREATE OR REPLACE TABLE DIM_REGION AS
SELECT
    R_REGIONKEY,
    R_NAME AS REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION;


CREATE OR REPLACE TABLE DIM_NATION AS
SELECT
    N_NATIONKEY,
    N_NAME      AS NATION,
    N_REGIONKEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION;


CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT
    C.C_CUSTKEY,
    C.C_NAME,
    C.C_MKTSEGMENT,
    C.C_NATIONKEY,
    N.N_NAME        AS CUSTOMER_NATION,
    R.R_NAME        AS CUSTOMER_REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION N
  ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION R
  ON N.N_REGIONKEY = R.R_REGIONKEY;


CREATE OR REPLACE TABLE DIM_SUPPLIER AS
SELECT
    S.S_SUPPKEY,
    S.S_NAME,
    S.S_NATIONKEY,
    N.N_NAME        AS SUPPLIER_NATION,
    R.R_NAME        AS SUPPLIER_REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER S
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION N
  ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION R
  ON N.N_REGIONKEY = R.R_REGIONKEY;


CREATE OR REPLACE TABLE DIM_PART AS
SELECT
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_BRAND,
    P_TYPE,
    P_SIZE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART;


CREATE OR REPLACE TABLE DIM_SHIP_MODE AS
SELECT DISTINCT
    L_SHIPMODE AS SHIP_MODE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
WHERE L_SHIPMODE IS NOT NULL;


CREATE OR REPLACE TABLE FACT_SALES AS
SELECT

    L.L_ORDERKEY,
    L.L_LINENUMBER,

    O.O_ORDERDATE                        AS ORDER_DATE,
    L.L_SHIPDATE                         AS SHIP_DATE,

    O.O_CUSTKEY                          AS C_CUSTKEY,
    L.L_SUPPKEY                          AS S_SUPPKEY,
    L.L_PARTKEY                          AS P_PARTKEY,
    L.L_SHIPMODE                         AS SHIP_MODE,

    L.L_QUANTITY,
    L.L_EXTENDEDPRICE                    AS GROSS_SALES,
    L.L_DISCOUNT,
    L.L_TAX,

    L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)                  AS NET_SALES,
    L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) * (1 + L.L_TAX)  AS NET_SALES_TAX,


    DATEDIFF('day', O.O_ORDERDATE, L.L_SHIPDATE)            AS DISPATCH_DAYS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM L
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS O
  ON L.L_ORDERKEY = O.O_ORDERKEY;
